version: 2.1
orbs:
  github-release: h-matsuo/github-release@0.1.1
jobs:
  build:
    working_directory: ~/overtheairbrew
    docker:
      - image: node:15
    environment:
      NODE_ENV: test
      LOGGING_LEVEL: info
    steps:
      - setup_remote_docker
      - checkout
      - run: echo 'export BUILD_NO=${CIRCLE_BUILD_NUM}.0.0' >> $BASH_ENV
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: |
            npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: |
            npm run build
      - run:
          name: Migrate Database
          command: npm run migrate
      - run:
          name: Test
          command: |
            npm run test
            npm run coverage
      - run:
          name: Prune Production
          command: npm prune --production
      - persist_to_workspace:
          root: ~/overtheairbrew
          paths:
            - .
  push_release:
    working_directory: ~/overtheairbrew
    docker:
      - image: node:15
    steps:
      - attach_workspace:
          at: ~/overtheairbrew
      - run:
          name: Package File
          command: |
            export PACKAGE_FILE="$(npm pack --ignore-scripts)";
      - github-release/create:
          tag: v${CIRCLE_TAG}
          title: Version v${CIRCLE_TAG}
          description: This release is version v${CIRCLE_TAG} .
          file-path: ./${PACKAGE_FILE}
workflows:
  version: 2
  build_release:
    jobs:
      - build:
          context: OVERTHEAIR_HOMEBREW
          filters:
            tags:
              only: /^v.*/
      - push_release:
          context: OVERTHEAIR_HOMEBREW
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
