version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:16'
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          MYSQL_DATABASE: circle_test
          DOCKER_REGISTRY_USER: sharpn
          DOCKER REGISTRY_PASSWORD: $GITHUB_PKG_AUTH_TOKEN
    environment:
      DB_URL: mysql://root@127.0.0.1/circle_test
      HUSKY: '0'
      CI: 'true'
    steps:
      - checkout
      - run:
          name: install
          command: npm ci
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: |
            npm run test
            npm run coverage
      - run:
          name: Prune
          command: npm prune --production
      - run:
          name: release
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
            npm run semantic-release || true

workflows:
  version: 2
  build_release:
    jobs:
      - build:
          context: OVERTHEAIR_HOMEBREW
