version: 2.1

jobs:
  build:
    working_directory: ~/overtheairbrew
    docker:
      - image: node:15
    environment:
      NODE_ENV: test
      LOGGING_LEVEL: info
    steps:
      - setup_remote_docker
      - checkout
      - run: echo 'export BUILD_NO=${CIRCLE_BUILD_NUM}.0.0' >> $BASH_ENV
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: |
            npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: |
            npm run build
      - run:
          name: Migrate Database
          command: npm run migrate
      - run:
          name: Test
          command: |
            npm run test
            npm run coverage
      - run:
          name: Prune Production
          command: npm prune --production
      - persist_to_workspace:
          root: ~/overtheairbrew
          paths:
            - .
  push_release:
    working_directory: ~/overtheairbrew
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: ~/overtheairbrew
      - run:
          name: Download ghr
          command: |
            go get github.com/tcnksm/ghr
      - run:
          name: deploy release
          command: |
            export PACKAGE_FILE="$(npm pack --ignore-scripts)";
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./${PACKAGE_FILE}
workflows:
  version: 2
  build_release:
    jobs:
      - build:
          context: OVERTHEAIR_HOMEBREW
          filters:
            tags:
              only: /^v.*/
      - push_release:
          context: OVERTHEAIR_HOMEBREW
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
