name: Build And Release

on: [ push ]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:16
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          MYSQL_DATABASE: test_database
    
    strategy:
      matrix: 
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - run: npm run migrate
      - run: npm run test:cov
        env:
          DB_URL: mysql://root@127.0.0.1/test_database
      - run: npm run test:e2e:cov
        env:
          DB_URL: mysql://root@127.0.0.1/test_database
      - uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true # optional (default = false)
      - run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT_AUTOMERGE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: '0'
          CI: 'true'
       