name: Build And Release

on: [ push ]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:16
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          MYSQL_DATABASE: test_database
    
    strategy:
      matrix: 
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - run: npm run test
        env:
          DB_URL: mysql://root@127.0.0.1/test_database
      - run: npm run coverage
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm run semantic-release || true
       